In [1]:
import numpy as np
np.random.seed(0)

In [2]:
image = np.random.randint(0, 10, size=(6, 6))

In [3]:
image

array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3]])

In [4]:
kernel = np.array([[1, 0, -1], [1, 0, -1], [1, 0, -1]])

In [5]:
kernel

array([[ 1,  0, -1],
       [ 1,  0, -1],
       [ 1,  0, -1]])

In [9]:
from scipy.signal import convolve

In [10]:
# Flip the kernel
kernel_flipped = np.negative(kernel)
convolve(image, kernel_flipped, 'valid')

array([[ -8,   0,   3,  11],
       [ -4,   2,  -3,   4],
       [ -7,   9,  -6,  -6],
       [ -6,   9, -12,  -3]])

In [35]:
image_example = np.array([
    [3, 0, 1, 2, 7, 4],
    [1, 5, 8, 9, 3, 1],
    [2, 7, 2, 5, 1, 3],
    [0, 1, 3, 1, 7, 8],
    [4, 2, 1, 6, 2, 8],
    [2, 4, 5, 2, 3, 9]
])

In [42]:
# Kernel is flipped by definition
kernel_flipped = np.negative(kernel)
convolve(image_example, kernel_flipped, mode='valid')

array([[ -5,  -4,   0,   8],
       [-10,  -2,   2,   3],
       [  0,  -2,  -4,  -7],
       [ -3,  -2,  -3, -16]])

### Naive implementation

In [27]:
def convolution_naive(image, kernel):
    output = np.zeros((image.shape[0] - kernel.shape[0] + 1,
                       image.shape[1] - kernel.shape[1] + 1))

    # walk over output rows
    for i in range(output.shape[0]):
        # walk over output columns
        for j in range(output.shape[1]):
            # walk over filter/kernel rows
            for k in range(kernel.shape[0]):
                # walk over filter/kernel columns
                for l in range(kernel.shape[1]):
                    image_x = i + k
                    image_y = j + l
                    output[i, j] += image[image_x, image_y] * kernel[k, l]
    
    return output

In [28]:
convolution_naive(image, kernel)

array([[  5.,  -1.,  -5.,   4.],
       [  7.,   2.,  -4.,   5.],
       [  2.,   6.,  -5.,  -7.],
       [  3.,   2.,   3., -10.]])

In [36]:
convolution_naive(image_example, kernel)

array([[ -5.,  -4.,   0.,   8.],
       [-10.,  -2.,   2.,   3.],
       [  0.,  -2.,  -4.,  -7.],
       [ -3.,  -2.,  -3., -16.]])