In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
image = np.random.randint(1, 10, (3, 3))

In [4]:
image

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5]])

In [6]:
np.pad(image, (1, 1), 'constant')

array([[0, 0, 0, 0, 0],
       [0, 6, 1, 4, 0],
       [0, 4, 8, 4, 0],
       [0, 6, 3, 5, 0],
       [0, 0, 0, 0, 0]])

In [13]:
pad = 2

In [14]:
np.pad(image, ((pad, pad), (pad, pad)), 'constant')

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 6, 1, 4, 0, 0],
       [0, 0, 4, 8, 4, 0, 0],
       [0, 0, 6, 3, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])